version: '3'

services:
    deploy-machine:
        build: ./services/motor
        devices:
            - /dev/gpiomem:/dev/gpiomem
    deploy-machine-frontend:
        build: ./services/frontend
        environment:
            - MOTOR_HOST=deploy-machine
        ports:
            - 80:80