version: '3'

services:
    deploy-machine:
        image: marcusthelin/deploy-machine
        devices:
            - /dev/gpiomem:/dev/gpiomem
    deploy-machine-frontend:
        image: marcusthelin/deploy-machine-frontend
        environment:
            - MOTOR_HOST=deploy-machine
        ports:
            - 80:80